// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3qlZsMcr9YreSWps2bywkv61Abn4n86s',
    appId: '1:769639627462:web:d1c459927fdfaf1c3e35c7',
    messagingSenderId: '769639627462',
    projectId: 'solution-challenge-2e259',
    authDomain: 'solution-challenge-2e259.firebaseapp.com',
    storageBucket: 'solution-challenge-2e259.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Ut3gLv2BWsPKMxh_xMACkv2GoqfEzdE',
    appId: '1:769639627462:android:53a1a8a84671ffae3e35c7',
    messagingSenderId: '769639627462',
    projectId: 'solution-challenge-2e259',
    storageBucket: 'solution-challenge-2e259.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa6xr0OWzO0sryLYx8mFeKrjWNX1Uplrc',
    appId: '1:769639627462:ios:b0676465a60d524e3e35c7',
    messagingSenderId: '769639627462',
    projectId: 'solution-challenge-2e259',
    storageBucket: 'solution-challenge-2e259.appspot.com',
    iosBundleId: 'com.example.solutionChallengFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa6xr0OWzO0sryLYx8mFeKrjWNX1Uplrc',
    appId: '1:769639627462:ios:9cee64c4d77e188d3e35c7',
    messagingSenderId: '769639627462',
    projectId: 'solution-challenge-2e259',
    storageBucket: 'solution-challenge-2e259.appspot.com',
    iosBundleId: 'com.example.solutionChallengFront.RunnerTests',
  );
}
